--- #YAML:1.0
name:               Thread-Cleanup
version:            0.01
abstract:           Hook thread destruction.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
    threads::shared:      0.91
requires:
    perl:      5.008
    threads:   1.07
    XSLoader:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Thread-Cleanup
    homepage:    http://search.cpan.org/dist/Thread-Cleanup/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/perl/modules/Thread-Cleanup.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
